# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
  - image: guestbook-backend
    context: src/backend
  - image: guestbook-frontend
    context: src/frontend
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: guestbook-dev
        chartPath: guestbook
        artifactOverrides: 
          frontendImageName: guestbook-frontend
          backendImageName: guestbook-backend
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}

